services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dbeac'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ROOT_PASSWORD='
      - 'MYSQL_USER='
    ports:
      - '3306'

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/microservices
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     database-platform: org.hibernate.dialect.MySQLDialect
#     hibernate:
#       ddl-auto: update
#     show-sql: true

#   application:
#     name: USER-SERVICE